CREATE DATABASE ECHECKIN;

USE ECHECKIN;

CREATE TABLE TBL_USUARIO(
	ID_USUARIO INT NOT NULL AUTO_INCREMENT,
	NOME VARCHAR(30),
	MATRICULA VARCHAR(30),
	EMPRESA INT,
	CARGO INT,
	LOGIN VARCHAR (20),
	SENHA VARCHAR (255),
	STATUS_USUARIO INT,
	PRIMARY KEY (ID_USUARIO),
	FOREIGN KEY (EMPRESA) REFERENCES TBL_EMPRESA(ID_EMPRESA),
	FOREIGN KEY (CARGO) REFERENCES TBL_CARGOS(ID_CARGO)
);

CREATE TABLE TBL_EMPRESA(
	ID_EMPRESA INT NOT NULL AUTO_INCREMENT,
	RAZAO_SOCIAL VARCHAR (30),
	CNPJ VARCHAR (18),
	STATUS_EMPRESA INT,
	PRIMARY KEY (ID_EMPRESA)
);

CREATE TABLE TBL_LOCAIS(
	ID_LOCAL INT NOT NULL AUTO_INCREMENT,
	ID_EMPRESA INT NOT NULL,
	TIPO_LOCAL INT NOT NULL,
	DESC_LOCAL VARCHAR(30),
	STATUS_LOCAL INT,
	PRIMARY KEY (ID_LOCAL)
);

CREATE TABLE TBL_CARGOS(
	ID_CARGO INT NOT NULL AUTO_INCREMENT,
	DESCRICAO_CARGO VARCHAR(30),
	STATUS_CARGO INT,
	PRIMARY KEY (ID_CARGO)
);

CREATE TABLE TBL_TIPOS_LOCAIS(
	ID_TIPOCARGO INT NOT NULL AUTO_INCREMENT,
	DESCRICAO_TIPOLOCAL VARCHAR(20),
	STATUS_TIPOLOCAL INT,
	PRIMARY KEY (ID_TIPOCARGO)
);

CREATE TABLE TBL_LOG(
	ID_LOG INT NOT NULL AUTO_INCREMENT,
	REGLOG TEXT,
	DATAHORA DATETIME,
	ID_USUARIO INT,
	PRIMARY KEY (ID_LOG),
	FOREIGN KEY (ID_USUARIO) REFERENCES TBL_USUARIO(ID_USUARIO)
);

INSERT INTO TBL_CARGOS (DESCRICAO_CARGO, STATUS_CARGO) VALUES ('CONTROLADOR DE ACESSO', '1');
INSERT INTO TBL_CARGOS (DESCRICAO_CARGO, STATUS_CARGO) VALUES ('OPERADOR DE ILHA', '1');
INSERT INTO TBL_CARGOS (DESCRICAO_CARGO, STATUS_CARGO) VALUES ('DESENVOLVEDOR', '1');
INSERT INTO TBL_CARGOS (DESCRICAO_CARGO, STATUS_CARGO) VALUES ('ADMINISTRADOR', '1');

INSERT INTO TBL_TIPOS_LOCAIS (DESCRICAO_TIPOLOCAL, STATUS_TIPOLOCAL) VALUES ('PONTO DE RONDA', '1');
INSERT INTO TBL_TIPOS_LOCAIS (DESCRICAO_TIPOLOCAL, STATUS_TIPOLOCAL) VALUES ('ILHA DE CARREGAMENTO / DESCARREGAMENTO', '1');

INSERT INTO TBL_EMPRESA(RAZAO_SOCIAL, CNPJ, STATUS_EMPRESA) VALUES ('PRODEV DESENVOLVIMENTO DE SISTEMAS', '39.345.960/0001-29', '1');
UPDATE TBL_USUARIO SET EMPRESA = 1 AND CARGO = 3 WHERE ID_USUARIO = 1
UPDATE TBL_USUARIO SET NOME= "Danilo Franco" WHERE ID_USUARIO = 1

INSERT INTO TBL_LOCAIS (FK_EMPRESA, FK_TIPO_LOCAL, DESC_LOCAL, STATUS_LOCAL) VALUES (1,1, 'LOCAL FICTICIO PARA TESTE', 1);
INSERT INTO TBL_LOCAIS (FK_EMPRESA, FK_TIPO_LOCAL, DESC_LOCAL, STATUS_LOCAL) VALUES (1,2, 'TESTE DE TRIGGER', 1);

/*
ALTER TABLE TBL_LOCAIS
ADD CONSTRAINT FK_EMPRESA FOREIGN KEY (FK_EMPRESA) REFERENCES TBL_EMPRESA(ID_EMPRESA),
ADD CONSTRAINT FK_TIPO_LOCAL FOREIGN KEY (FK_TIPO_LOCAL) REFERENCES TBL_LOCAIS(ID_TIPO_LOCAL);
*/

/*
ALTER TABLE TBL_TIPOS_LOCAIS
CHANGE COLUMN ID_TIPOCARGO ID_TIPO_LOCAL INT;
*/

ALTER TABLE TBL_CARGOS
CHANGE COLUMN NIVEL_ACESSO FK_NIVEL_ACESSO INT;

ALTER TABLE TBL_CARGOS
ADD CONSTRAINT FK_NIVEIS_ACESSO FOREIGN KEY (FK_NIVEL_ACESSO) REFERENCES TBL_NIVEIS_ACESSO(ID_NIVEL_ACESSO);

CREATE TABLE TBL_CHECKIN(
	ID_CHECKIN INT NOT NULL AUTO_INCREMENT,
	FK_LOCAL INT NOT NULL,
	FK_USUARIO INT NOT NULL,
	DATAHORA_CHECKIN DATETIME NOT NULL,
	PRIMARY KEY(ID_CHECKIN),
	FOREIGN KEY (FK_LOCAL) REFERENCES TBL_LOCAIS(ID_LOCAL),
	FOREIGN KEY (FK_USUARIO) REFERENCES TBL_USUARIO(ID_USUARIO)
);

CREATE TABLE TBL_ERRO(
	ID_ERRO INT NOT NULL AUTO_INCREMENT,
	DESC_ERRO TEXT NOT NULL,
	LOCAL TEXT NOT NULL,
	DATA DATETIME NOT NULL,
	FK_USUARIO INT NOT NULL,
	PRIMARY KEY (ID_ERRO),
	FOREIGN KEY (FK_USUARIO) REFERENCES TBL_USUARIO(ID_USUARIO)
);

ALTER TABLE TBL_EMPRESA 
ADD COLUMN QTD_LOCAIS INT;

SELECT 
    TBL_LOCAIS.ID_LOCAL,
    TBL_TIPOS_LOCAIS.DESCRICAO_TIPOLOCAL,
    TBL_LOCAIS.FK_EMPRESA,
    TBL_LOCAIS.DESC_LOCAL,
    TBL_LOCAIS.STATUS_LOCAL    
FROM 
    TBL_LOCAIS
JOIN 
    TBL_TIPOS_LOCAIS ON TBL_LOCAIS.FK_TIPO_LOCAL = TBL_TIPOS_LOCAIS.ID_TIPO_LOCAL;

ALTER TABLE TBL_CARGOS
ADD COLUMN NIVEL_ACESSO INT;

CREATE TABLE TBL_NIVEIS_ACESSO(
	ID_NIVEL_ACESSO INT NOT NULL AUTO_INCREMENT,
	DESC_NIVEL_ACESSO VARCHAR(20),
	PRIMARY KEY (ID_NIVEL_ACESSO)
);